### ISSUE TITLE
Please tag the source

### ISSUE THREAD

**Issue by fabaff** [andrewgierens/tessie_python_api#3]
It would be very helpful if you could tag releases as well. This would enable distributions to fetch the source from GitHub instead of PyPI.

Thanks

**Comment by andrewgierens** [comment]
Will do - Ill post here once its done, I planned on doing this after the initial release. Thanks for the recommendation

**Comment by andrewgierens** [comment]
@fabaff Have a look at the latest release and let me know if you think I should add anything else :) (Im new to python deployments)
